questions = {
    "Physics": {
        "Easy": [
            ("Q1. What is the SI unit of force?", ["A) Newton(N)", "B) Joule(J)", "C) Watt(W)", "D) Pascal(Pa)"], "A) Newton(N)"),
            ("Q2. Which of the following is a vector quantity?", ["A) Speed", "B) Temperature", "C) Acceleration", "D) Energy"], "C) Acceleration"),
            ("Q3. What is the formula for calculating work done?", ["A) Force x Distance", "B) Mass x Acceleration", "C) Speed x Time", "D) Voltage x Current"], "A) Force x Distance"),
            ("Q4. What is the SI unit of energy?", ["A) Newton (N)", "B) Kelvin(K)", "C) Joule(J)", "D) Pascal(Pa)"], "C) Joule(J)"),
            ("Q5. Which of the following is a renewable source of energy?", ["A) Coal", "B) Natural Gas", "C) Solar", "D) Petroleum"], "C) Solar"),
            ("Q6. What is the acceleration due to gravity on Earth?", ["A) 9.8m/s^2", "B) 6.8m/s^2", "C) 10 m/s^2", "D) 7.8m/s^2"], "A) 9.8m/s^2"),
            ("Q7. Which law states that every action has an equal and opposite reaction?", ["A) Newton's First Law", "B) Newton's Second Law", "C) Newton's Third Law", "D) Boyle's Law"], "C) Newton's Third Law"),
            ("Q8. What is the formula for calculating speed?", ["A) Speed = Distance x Time", "B) Speed = Distance / Time", "C) Speed = Time / Distance", "D) Speed = Time x Velocity"], "B) Speed = Distance / Time"),
            ("Q9. What is the unit of electric current?", ["A) Volts(V)", "B) Ampere(A)", "C) Ohm(Ω)", "D) Watt(W)"], "B) Ampere(A)"),
            ("Q10. What is the formula for density?", ["A) Density = Mass x Volume", "B) Density = Volume / Mass", "C) Density = Mass / Volume", "D) Density = Volume x Mass"], "C) Density = Mass / Volume"),
            ("Q11. What is the formula for calculating power?", ["A) Power = Force x Distance", "B) Power = Work / Time", "C) Power = Voltage x Current", "D) Power = Mass x Acceleration"], "B) Power = Work / Time"),
            ("Q12. Which of the following is a non-renewable source of energy?", ["A) Wind", "B) Hydroelectric", "C) Coal", "D) Biomass"], "C) Coal"),
            ("Q13. What is the formula for calculating kinetic energy?", ["A) Kinetic Energy = 1/2 x Mass x Velocity^2", "B) Kinetic Energy = Mass x Velocity", "C) Kinetic Energy = Mass x Velocity^2", "D) Kinetic Energy = 1/2 x Mass x Velocity"], "A) Kinetic Energy = 1/2 x Mass x Velocity^2"),
            ("Q14. What is the SI unit of power?", ["A) Newton(N)", "B) Watt(W)", "C) Joule(J)", "D) Pascal(Pa)"], "B) Watt(W)"),
            ("Q15. What is the formula for calculating force?", ["A) Force = Mass x Acceleration", "B) Force = Mass x Velocity", "C) Force = Velocity / Time", "D) Force = Work / Distance"], "A) Force = Mass x Acceleration"),
            ("Q16. Which of the following is an example of a contact force?", ["A) Gravitational force", "B) Magnetic force", "C) Frictional force", "D) Electrostatic force"], "C) Frictional force"),
            ("Q17. What is the formula for calculating pressure?", ["A) Pressure = Force x Area", "B) Pressure = Work / Volume", "C) Pressure = Force / Area", "D) Pressure = Volume / Force"], "C) Pressure = Force / Area"),
            ("Q18. What is the unit of pressure?", ["A) Pascal(Pa)", "B) Newton(N)", "C) Joule(J)", "D) Watt(W)"], "A) Pascal(Pa)"),
            ("Q19. Which of the following is a scalar quantity?", ["A) Velocity", "B) Force", "C) Speed", "D) Acceleration"], "C) Speed"),
            ("Q20. What is the formula for calculating momentum?", ["A) Momentum = Mass x Acceleration", "B) Momentum = Force x Time", "C) Momentum = Mass x Vel", "D) Momentum = Vel / Time"], "C) Momentum = Mass x Vel"),
        ],
        "Medium": [
            ("Q1. What is the SI unit of power?", ["A) Newton(N)", "B) Watt(W)", "C) Joule(J)", "D) Pascal(Pa)"], "B) Watt(W)"),
            ("Q2. Which of the following is a derived unit?", ["A) Meter", "B) Second", "C) Newton", "D) Joule"], "C) Newton"),
            ("Q3. What does Ohm's Law state?", ["A) V = IR", "B) P = VI", "C) I = VR", "D) V = I^2R"], "A) V = IR"),
            ("Q4. What is the formula for calculating kinetic energy?", ["A) KE = 1/2mv^2", "B) KE = mgh", "C) KE = 1/2mv", "D) KE = m/v^2"], "A) KE = 1/2mv^2"),
            ("Q5. What is the law of conservation of energy?", ["A) Energy cannot be created or destroyed", "B) Energy can be created", "C) Energy can be destroyed", "D) Energy is not conserved"], "A) Energy cannot be created or destroyed"),
            ("Q6. What is the SI unit of electric charge?", ["A) Ampere(A)", "B) Coulomb(C)", "C) Volt(V)", "D) Ohm(Ω)"], "B) Coulomb(C)"),
            ("Q7. What is the formula for calculating electric power?", ["A) P = IV", "B) P = I^2R", "C) P = V^2/R", "D) P = RI^2"], "C) P = V^2/R"),
            ("Q8. Which of the following is a unit of capacitance?", ["A) Ohm(Ω)", "B) Volt(V)", "C) Farad(F)", "D) Ampere(A)"], "C) Farad(F)"),
            ("Q9. What is the relationship between current, voltage, and resistance in a circuit?", ["A) V = IR", "B) V = I/R", "C) V = I + R", "D) V = I^2R"], "A) V = IR"),
            ("Q10. What is the principle of conservation of momentum?", ["A) Momentum is always conserved", "B) Momentum is created", "C) Momentum is destroyed", "D) Momentum is variable"], "A) Momentum is always conserved"),
            ("Q11. What is the formula for calculating potential energy?", ["A) PE = mgh", "B) PE = 1/2mv^2", "C) PE = m/v^2", "D) PE = mgh^2"], "A) PE = mgh"),
            ("Q12. Which of the following is a non-conservative force?", ["A) Friction", "B) Gravity", "C) Tension", "D) Normal force"], "A) Friction"),
            ("Q13. What is the formula for calculating resistance in a circuit?", ["A) R = V/I", "B) R = I/V", "C) R = V + I", "D) R = VI"], "A) R = V/I"),
            ("Q14. What is the unit of electric potential difference?", ["A) Volt(V)", "B) Ampere(A)", "C) Coulomb(C)", "D) Ohm(Ω)"], "A) Volt(V)"),
            ("Q15. Which of the following is a unit of magnetic field strength?", ["A) Ampere-turn/meter (At/m)", "B) Tesla(T)", "C) Newton (N)", "D) Joule(J)"], "A) Ampere-turn/meter (At/m)"),
            ("Q16. What is the formula for calculating gravitational force?", ["A) F = GMm/r^2", "B) F = ma", "C) F = Gm^2/r^2", "D) F = mg"], "A) F = GMm/r^2"),
            ("Q17. What is the SI unit of magnetic flux?", ["A) Weber(Wb)", "B) Tesla(T)", "C) Henry(H)", "D) Gauss(G)"], "A) Weber(Wb)"),
            ("Q18. Which of the following is a unit of inductance?", ["A) Farad(F)", "B) Ohm(Ω)", "C) Henry(H)", "D) Tesla(T)"], "C) Henry(H)"),
            ("Q19. What is the formula for calculating torque?", ["A) τ = Fd", "B) τ = F/a", "C) τ = Fd sin(θ)", "D) τ = Fd cos(θ)"], "C) τ = Fd sin(θ)"),
            ("Q20. What is the formula for calculating angular momentum?", ["A) L = Iω", "B) L = mv", "C) L = Fd", "D) L = τ/t"], "A) L = Iω")
            
        ],
        "Hard": [
            ("Q1. What is the formula for calculating angular acceleration?", ["A) α = Δθ/Δt", "B) α = v^2/r", "C) α = Δv/Δt", "D) α = rω"], "A) α = Δθ/Δt"),
            ("Q2. What is the SI unit of magnetic flux density?", ["A) Weber/meter^2 (Wb/m^2)", "B) Tesla(T)", "C) Weber(Wb)", "D) Gauss(G)"], "B) Tesla(T)"),
            ("Q3. What is the formula for calculating electric field strength?", ["A) E = V/d", "B) E = Q/ε₀A", "C) E = F/q", "D) E = kQ/r^2"], "B) E = Q/ε₀A"),
            ("Q4. What is the relationship between frequency and wavelength of a wave?", ["A) Inversely proportional", "B) Directly proportional", "C) No relationship", "D) Square of each other"], "A) Inversely proportional"),
            ("Q5. What does the term 'hertz' represent?", ["A) Unit of energy", "B) Unit of frequency", "C) Unit of power", "D) Unit of distance"], "B) Unit of frequency"),
            ("Q6. What is the formula for calculating the period of a pendulum?", ["A) T = 2π√(L/g)", "B) T = 2π/√(L/g)", "C) T = π√(L/g)", "D) T = π/√(L/g)"], "A) T = 2π√(L/g)"),
            ("Q7. What is the formula for calculating the electric potential due to a point charge?", ["A) V = kQ/r^2", "B) V = kQ/r", "C) V = kQ/r^3", "D) V = kQ^2/r"], "B) V = kQ/r"),
            ("Q8. What is the principle behind the operation of a transformer?", ["A) Induction", "B) Convection", "C) Radiation", "D) Conduction"], "A) Induction"),
            ("Q9. What is the formula for calculating the energy stored in a capacitor?", ["A) E = 1/2CV^2", "B) E = 1/2QV", "C) E = 1/2C^2V", "D) E = Q^2/C"], "A) E = 1/2CV^2"),
            ("Q10. What is the relationship between resistance and temperature in a conductor?", ["A) Directly proportional", "B) Inversely proportional", "C) No relationship", "D) Exponential"], "A) Directly proportional"),
            ("Q11. What is the formula for calculating the maximum height reached by a projectile?", ["A) H = (v₀^2 sin²θ)/(2g)", "B) H = (v₀^2 sinθ)/(2g)", "C) H = (v₀^2 cosθ)/(2g)", "D) H = (v₀^2)/(2g)"], "A) H = (v₀^2 sin²θ)/(2g)"),
            ("Q12. What is the SI unit of electric field strength?", ["A) Volt(V)/meter", "B) Newton/Coulomb(N/C)", "C) Joule/Coulomb(J/C)", "D) Coulomb/meter(C/m)"], "A) Volt(V)/meter"),
            ("Q13. What is the formula for calculating the force exerted by a magnetic field on a current-carrying wire?", ["A) F = BIL", "B) F = BIL sin(θ)", "C) F = BIL cos(θ)", "D) F = BI²L"], "B) F = BIL sin(θ)"),
            ("Q14. What is the principle behind the operation of a laser?", ["A) Stimulated emission of radiation", "B) Absorption of radiation", "C) Reflection of radiation", "D) Scattering of radiation"], "A) Stimulated emission of radiation"),
            ("Q15. What is the formula for calculating the moment of inertia of a uniform rod about its end?", ["A) I = (1/3)ML²", "B) I = (1/12)ML²", "C) I = (1/2)ML²", "D) I = ML²"], "B) I = (1/12)ML²"),
            ("Q16. What is the relationship between pressure and volume in Boyle's Law?", ["A) Directly proportional", "B) Inversely proportional", "C) No relationship", "D) Exponential"], "B) Inversely proportional"),
            ("Q17. What is the formula for calculating the work done by a variable force?", ["A) W = ∫Fdx", "B) W = Fd", "C) W = ∫dx/F", "D) W = F^2d"], "A) W = ∫Fdx"),
            ("Q18. What is the formula for calculating the frequency of a wave?", ["A) f = v/λ", "B) f = λ/v", "C) f = vλ", "D) f = v^2/λ"], "A) f = v/λ"),
            ("Q19. What is the principle behind the operation of a Geiger counter?", ["A) Ionization of gas", "B) Reflection of radiation", "C) Conduction of radiation", "D) Absorption of radiation"], "A) Ionization of gas"),
            ("Q20. What is the formula for calculating the period of a mass-spring system?", ["A) T = 2π√(m/k)", "B) T = 2π/√(m/k)", "C) T = π√(m/k)", "D) T = π/√(m/k)"], "A) T = 2π√(m/k)")

        ]
    },
    "Chemistry": {
        "Easy": [
            ("Q1. What is the chemical symbol for gold?", ["A) Au", "B) Ag", "C) Fe", "D) Cu"], "A) Au"),
            ("Q2. What is the pH value of a neutral solution?", ["A) 7", "B) 0", "C) 14", "D) 10"], "A) 7"),
            ("Q3. What is the chemical formula for water?", ["A) H2O", "B) CO2", "C) NaCl", "D) H2SO4"], "A) H2O"),
            ("Q4. Which gas is responsible for the greenhouse effect?", ["A) Carbon dioxide", "B) Oxygen", "C) Nitrogen", "D) Helium"], "A) Carbon dioxide"),
            ("Q5. What is the atomic number of carbon?", ["A) 6", "B) 8", "C) 12", "D) 16"], "A) 6"),
            ("Q6. What is the chemical name of baking soda?", ["A) Sodium chloride", "B) Sodium bicarbonate", "C) Sodium hydroxide", "D) Sodium carbonate"], "B) Sodium bicarbonate"),
            ("Q7. Which gas is produced during photosynthesis?", ["A) Oxygen", "B) Carbon dioxide", "C) Nitrogen", "D) Hydrogen"], "A) Oxygen"),
            ("Q8. What is the chemical formula for methane?", ["A) CH4", "B) CO2", "C) H2O", "D) NH3"], "A) CH4"),
            ("Q9. What is the chemical name of table salt?", ["A) Sodium chloride", "B) Sodium bicarbonate", "C) Sodium hydroxide", "D) Sodium carbonate"], "A) Sodium chloride"),
            ("Q10. Which element is the most abundant in the Earth's atmosphere?", ["A) Nitrogen", "B) Oxygen", "C) Carbon dioxide", "D) Argon"], "A) Nitrogen"),
            ("Q11. What is the chemical formula for sulfuric acid?", ["A) H2SO4", "B) HCl", "C) HNO3", "D) NaOH"], "A) H2SO4"),
            ("Q12. What is the chemical formula for hydrogen peroxide?", ["A) H2O", "B) H2O2", "C) HO2", "D) H2SO4"], "B) H2O2"),
            ("Q13. What is the chemical symbol for silver?", ["A) Ag", "B) Au", "C) Cu", "D) Fe"], "A) Ag"),
            ("Q14. Which gas is used for extinguishing fires?", ["A) Carbon dioxide", "B) Oxygen", "C) Nitrogen", "D) Hydrogen"], "A) Carbon dioxide"),
            ("Q15. What is the chemical formula for ammonia?", ["A) NH3", "B) HCl", "C) NaOH", "D) CH4"], "A) NH3"),
            ("Q16. Which gas is produced when an acid reacts with a metal?", ["A) Hydrogen", "B) Oxygen", "C) Nitrogen", "D) Carbon dioxide"], "A) Hydrogen"),
            ("Q17. What is the chemical symbol for iron?", ["A) Fe", "B) Au", "C) Ag", "D) Cu"], "A) Fe"),
            ("Q18. What is the chemical formula for carbon dioxide?", ["A) CO2", "B) H2O", "C) CH4", "D) CO"], "A) CO2"),
            ("Q19. What is the chemical formula for hydrochloric acid?", ["A) HCl", "B) H2SO4", "C) NaOH", "D) NH3"], "A) HCl"),
            ("Q20. Which gas is commonly used in carbonated drinks?", ["A) Carbon dioxide", "B) Oxygen", "C) Nitrogen", "D) Hydrogen"], "A) Carbon dioxide")
        ],
        "Medium": [
            ("Q1. What is the primary component of natural gas?", ["A) Methane", "B) Ethane", "C) Propane", "D) Butane"], "A) Methane"),
            ("Q2. What is the chemical formula for acetic acid?", ["A) CH3COOH", "B) H2CO3", "C) C2H5OH", "D) CH4"], "A) CH3COOH"),
            ("Q3. What type of bond is formed between two atoms when they share electrons?", ["A) Ionic bond", "B) Covalent bond", "C) Hydrogen bond", "D) Metallic bond"], "B) Covalent bond"),
            ("Q4. What is the oxidation state of sulfur in sulfuric acid (H2SO4)?", ["A) +2", "B) +4", "C) +6", "D) -2"], "C) +6"),
            ("Q5. Which element has the highest electronegativity?", ["A) Fluorine", "B) Oxygen", "C) Nitrogen", "D) Chlorine"], "A) Fluorine"),
            ("Q6. What is the name of the compound with the chemical formula KNO3?", ["A) Potassium nitrate", "B) Potassium nitrite", "C) Sodium nitrate", "D) Sodium nitrite"], "A) Potassium nitrate"),
            ("Q7. What is the pH of a solution with a hydrogen ion concentration of 1 x 10^-3 M?", ["A) 3", "B) 7", "C) 10", "D) 14"], "A) 3"),
            ("Q8. What is the molarity of a solution containing 1 mole of solute in 1 liter of solution?", ["A) 0.5 M", "B) 1 M", "C) 2 M", "D) 3 M"], "B) 1 M"),
            ("Q9. Which type of chemical reaction involves the exchange of ions between two compounds?", ["A) Synthesis", "B) Decomposition", "C) Single replacement", "D) Double replacement"], "D) Double replacement"),
            ("Q10. What is the common name for the compound with the chemical formula NH4OH?", ["A) Ammonium nitrate", "B) Ammonium hydroxide", "C) Ammonium chloride", "D) Ammonium sulfate"], "B) Ammonium hydroxide"),
            ("Q11. In a redox reaction, what happens to the substance that is reduced?", ["A) It gains electrons", "B) It loses electrons", "C) It gains protons", "D) It loses protons"], "A) It gains electrons"),
            ("Q12. What is the molecular geometry of carbon dioxide (CO2)?", ["A) Bent", "B) Tetrahedral", "C) Linear", "D) Trigonal planar"], "C) Linear"),
            ("Q13. What is the primary use of sulfuric acid in industry?", ["A) Fertilizer production", "B) Food preservation", "C) Water treatment", "D) Cleaning agents"], "A) Fertilizer production"),
            ("Q14. What is the term for a solution that resists changes in pH when small amounts of acid or base are added?", ["A) Buffer", "B) Catalyst", "C) Solvent", "D) Electrolyte"], "A) Buffer"),
            ("Q15. What is the formula mass of sodium chloride (NaCl)?", ["A) 23 g/mol", "B) 35.5 g/mol", "C) 58.5 g/mol", "D) 60 g/mol"], "C) 58.5 g/mol"),
            ("Q16. What is the name of the process by which a liquid turns into a gas at a temperature below its boiling point?", ["A) Evaporation", "B) Condensation", "C) Sublimation", "D) Deposition"], "A) Evaporation"),
            ("Q17. What is the main component of limestone?", ["A) Calcium carbonate", "B) Calcium sulfate", "C) Calcium chloride", "D) Calcium nitrate"], "A) Calcium carbonate"),
            ("Q18. What type of reaction is represented by the equation: 2H2 + O2 -> 2H2O?", ["A) Synthesis", "B) Decomposition", "C) Single replacement", "D) Double replacement"], "A) Synthesis"),
            ("Q19. Which element is known as the 'king of chemicals' due to its widespread use in the chemical industry?", ["A) Hydrogen", "B) Sulfur", "C) Oxygen", "D) Nitrogen"], "B) Sulfur"),
            ("Q20. What is the name of the organic functional group -COOH?", ["A) Alcohol", "B) Aldehyde", "C) Carboxyl", "D) Ketone"], "C) Carboxyl"),
        ],
        "Hard": [
            ("Q1. What is the name of the theory that explains the behavior of electrons in atoms as both particles and waves?", ["A) Quantum theory", "B) Relativity theory", "C) Kinetic theory", "D) Atomic theory"], "A) Quantum theory"),
            ("Q2. What is the term for the measure of the randomness or disorder of a system?", ["A) Enthalpy", "B) Entropy", "C) Gibbs free energy", "D) Internal energy"], "B) Entropy"),
            ("Q3. What is the hybridization of the central atom in methane (CH4)?", ["A) sp", "B) sp2", "C) sp3", "D) dsp3"], "C) sp3"),
            ("Q4. What is the common name for the compound with the chemical formula C6H6?", ["A) Benzene", "B) Toluene", "C) Xylene", "D) Phenol"], "A) Benzene"),
            ("Q5. In the context of acid-base chemistry, what is the conjugate base of H2SO4?", ["A) HSO4-", "B) SO4^2-", "C) H3SO4+", "D) OH-"], "A) HSO4-"),
            ("Q6. What is the order of the reaction with respect to the reactant A if doubling the concentration of A doubles the rate of the reaction?", ["A) Zero order", "B) First order", "C) Second order", "D) Third order"], "B) First order"),
            ("Q7. What is the primary distinction between a sigma bond and a pi bond?", ["A) Sigma bonds involve side-to-side overlap of orbitals", "B) Pi bonds involve head-to-head overlap of orbitals", "C) Sigma bonds involve head-to-head overlap of orbitals", "D) Pi bonds involve end-to-end overlap of orbitals"], "C) Sigma bonds involve head-to-head overlap of orbitals"),
            ("Q8. What is the principal quantum number for the outermost electrons in an atom of calcium?", ["A) 2", "B) 3", "C) 4", "D) 5"], "C) 4"),
            ("Q9. What is the name of the process by which a solid turns directly into a gas?", ["A) Sublimation", "B) Deposition", "C) Condensation", "D) Melting"], "A) Sublimation"),
            ("Q10. What is the standard enthalpy change of formation for an element in its standard state?", ["A) 0 kJ/mol", "B) 25 kJ/mol", "C) 50 kJ/mol", "D) 100 kJ/mol"], "A) 0 kJ/mol"),
            ("Q11. What is the maximum number of electrons that can occupy a single orbital?", ["A) 1", "B) 2", "C) 4", "D) 6"], "B) 2"),
            ("Q12. What is the term for a substance that speeds up a chemical reaction without being consumed?", ["A) Solvent", "B) Catalyst", "C) Reactant", "D) Product"], "B) Catalyst"),
            ("Q13. What is the chemical formula for the chromate ion?", ["A) CrO4^2-", "B) Cr2O7^2-", "C) Cr3+", "D) CrO3"], "A) CrO4^2-"),
            ("Q14. Which principle states that no two electrons in an atom can have the same set of four quantum numbers?", ["A) Aufbau principle", "B) Pauli exclusion principle", "C) Hund's rule", "D) Heisenberg uncertainty principle"], "B) Pauli exclusion principle"),
            ("Q15. What is the term for the energy required to remove an electron from a gaseous atom or ion?", ["A) Electron affinity", "B) Electronegativity", "C) Ionization energy", "D) Lattice energy"], "C) Ionization energy"),
            ("Q16. What is the geometry of the SF6 molecule?", ["A) Octahedral", "B) Tetrahedral", "C) Trigonal bipyramidal", "D) Square planar"], "A) Octahedral"),
            ("Q17. What is the coordination number of the central atom in [Fe(CN)6]^4-?", ["A) 2", "B) 4", "C) 6", "D) 8"], "C) 6"),
            ("Q18. Which law states that the pressure of a given mass of gas is directly proportional to its absolute temperature, provided the volume remains constant?", ["A) Boyle's law", "B) Charles's law", "C) Gay-Lussac's law", "D) Avogadro's law"], "C) Gay-Lussac's law"),
            ("Q19. What is the primary product formed when benzene reacts with chlorine in the presence of a catalyst such as iron (III) chloride?", ["A) Chlorobenzene", "B) Benzyl chloride", "C) Dichlorobenzene", "D) Phenol"], "A) Chlorobenzene"),
            ("Q20. What is the name of the process by which isotopes of uranium are separated for use in nuclear reactors?", ["A) Distillation", "B) Electrophoresis", "C) Centrifugation", "D) Enrichment"], "D) Enrichment"),
        ]
    },
    "Biology": {
        "Easy": [
            ("Q1. What is the basic unit of life?", ["A) Atom", "B) Cell", "C) Tissue", "D) Organ"], "B) Cell"),
            ("Q2. Which organelle is known as the powerhouse of the cell?", ["A) Nucleus", "B) Chloroplast", "C) Mitochondrion", "D) Ribosome"], "C) Mitochondrion"),
            ("Q3. What is the chemical formula for glucose?", ["A) C6H12O6", "B) H2O", "C) CO2", "D) O2"], "A) C6H12O6"),
            ("Q4. Which molecule carries genetic information?", ["A) RNA", "B) DNA", "C) Protein", "D) Lipid"], "B) DNA"),
            ("Q5. What is the process by which plants make their own food?", ["A) Respiration", "B) Photosynthesis", "C) Digestion", "D) Fermentation"], "B) Photosynthesis"),
            ("Q6. What type of organism is yeast?", ["A) Bacteria", "B) Virus", "C) Fungus", "D) Algae"], "C) Fungus"),
            ("Q7. Which part of the plant is responsible for photosynthesis?", ["A) Root", "B) Stem", "C) Leaf", "D) Flower"], "C) Leaf"),
            ("Q8. What is the main function of red blood cells?", ["A) Fight infection", "B) Carry oxygen", "C) Clot blood", "D) Produce hormones"], "B) Carry oxygen"),
            ("Q9. What is the name of the process by which a cell divides into two daughter cells?", ["A) Meiosis", "B) Mitosis", "C) Binary fission", "D) Budding"], "B) Mitosis"),
            ("Q10. Which part of the brain controls balance and coordination?", ["A) Cerebrum", "B) Cerebellum", "C) Brainstem", "D) Hypothalamus"], "B) Cerebellum"),
            ("Q11. What is the largest organ in the human body?", ["A) Heart", "B) Liver", "C) Skin", "D) Lungs"], "C) Skin"),
            ("Q12. Which vitamin is produced when the skin is exposed to sunlight?", ["A) Vitamin A", "B) Vitamin B12", "C) Vitamin C", "D) Vitamin D"], "D) Vitamin D"),
            ("Q13. What is the name of the pigment that gives skin its color?", ["A) Hemoglobin", "B) Chlorophyll", "C) Melanin", "D) Keratin"], "C) Melanin"),
            ("Q14. What is the smallest bone in the human body?", ["A) Stapes", "B) Femur", "C) Radius", "D) Ulna"], "A) Stapes"),
            ("Q15. What type of macromolecule are enzymes?", ["A) Carbohydrates", "B) Lipids", "C) Proteins", "D) Nucleic acids"], "C) Proteins"),
            ("Q16. What is the name of the process by which plants lose water vapor through their leaves?", ["A) Transpiration", "B) Photosynthesis", "C) Respiration", "D) Germination"], "A) Transpiration"),
            ("Q17. Which blood type is known as the universal donor?", ["A) A", "B) B", "C) AB", "D) O"], "D) O"),
            ("Q18. Which organ is primarily responsible for detoxifying chemicals and metabolizing drugs?", ["A) Kidney", "B) Liver", "C) Pancreas", "D) Heart"], "B) Liver"),
            ("Q19. What is the term for animals that can live both in water and on land?", ["A) Amphibians", "B) Reptiles", "C) Mammals", "D) Birds"], "A) Amphibians"),
            ("Q20. What is the name of the process by which green plants convert carbon dioxide and water into glucose and oxygen using sunlight?", ["A) Respiration", "B) Photosynthesis", "C) Fermentation", "D) Transpiration"], "B) Photosynthesis")
        ],
        "Medium": [
            ("Q1. What is the primary function of the mitochondria in eukaryotic cells?", ["A) Photosynthesis", "B) Protein synthesis", "C) Cellular respiration", "D) Lipid synthesis"], "C) Cellular respiration"),
            ("Q2. Which molecule acts as the main energy currency in cells?", ["A) NADH", "B) ATP", "C) Glucose", "D) GTP"], "B) ATP"),
            ("Q3. In which phase of the cell cycle does DNA replication occur?", ["A) G1 phase", "B) S phase", "C) G2 phase", "D) M phase"], "B) S phase"),
            ("Q4. What is the process by which cells become specialized in structure and function?", ["A) Differentiation", "B) Apoptosis", "C) Mitosis", "D) Meiosis"], "A) Differentiation"),
            ("Q5. Which type of RNA carries amino acids to the ribosome during protein synthesis?", ["A) mRNA", "B) tRNA", "C) rRNA", "D) miRNA"], "B) tRNA"),
            ("Q6. What is the role of the enzyme helicase in DNA replication?", ["A) Synthesizing new DNA strands", "B) Unwinding the DNA double helix", "C) Sealing Okazaki fragments", "D) Preventing DNA tangling"], "B) Unwinding the DNA double helix"),
            ("Q7. What is the main function of the large intestine in the human digestive system?", ["A) Absorbing nutrients", "B) Absorbing water and electrolytes", "C) Digesting proteins", "D) Producing bile"], "B) Absorbing water and electrolytes"),
            ("Q8. Which plant hormone is responsible for promoting cell elongation and is often used in rooting compounds?", ["A) Cytokinin", "B) Gibberellin", "C) Auxin", "D) Ethylene"], "C) Auxin"),
            ("Q9. What is the term for the symbiotic relationship where both organisms benefit?", ["A) Parasitism", "B) Commensalism", "C) Mutualism", "D) Amensalism"], "C) Mutualism"),
            ("Q10. In genetic terms, what is an allele?", ["A) A type of protein", "B) A variant form of a gene", "C) A section of a chromosome", "D) A type of RNA"], "B) A variant form of a gene"),
            ("Q11. What is the primary function of the rough endoplasmic reticulum in a cell?", ["A) Lipid synthesis", "B) Protein synthesis", "C) ATP production", "D) DNA replication"], "B) Protein synthesis"),
            ("Q12. What is the primary function of the lymphatic system?", ["A) Transporting oxygen", "B) Filtering blood", "C) Fighting infections", "D) Producing hormones"], "C) Fighting infections"),
            ("Q13. Which process describes the movement of molecules from an area of high concentration to an area of low concentration?", ["A) Active transport", "B) Diffusion", "C) Osmosis", "D) Endocytosis"], "B) Diffusion"),
            ("Q14. What is the role of ribosomal RNA (rRNA) in cells?", ["A) Carrying genetic information", "B) Catalyzing protein synthesis", "C) Transporting amino acids", "D) Replicating DNA"], "B) Catalyzing protein synthesis"),
            ("Q15. Which gland in the human body produces insulin?", ["A) Thyroid gland", "B) Adrenal gland", "C) Pituitary gland", "D) Pancreas"], "D) Pancreas"),
            ("Q16. What is the primary function of myelin in the nervous system?", ["A) Transmitting nerve impulses", "B) Insulating nerve fibers", "C) Producing neurotransmitters", "D) Regulating ion exchange"], "B) Insulating nerve fibers"),
            ("Q17. Which molecule is known as the 'universal solvent' due to its ability to dissolve many substances?", ["A) Ethanol", "B) Acetone", "C) Water", "D) Benzene"], "C) Water"),
            ("Q18. What is the primary function of the kidneys in the human body?", ["A) Regulating blood pressure", "B) Filtering waste from the blood", "C) Producing red blood cells", "D) Storing nutrients"], "B) Filtering waste from the blood"),
            ("Q19. Which structure in the human eye is responsible for focusing light onto the retina?", ["A) Cornea", "B) Lens", "C) Iris", "D) Pupil"], "B) Lens"),
            ("Q20. What is the primary function of the spleen in the lymphatic system?", ["A) Producing white blood cells", "B) Filtering blood and removing old red blood cells", "C) Storing platelets", "D) Regulating blood sugar levels"], "B) Filtering blood and removing old red blood cells")
],
        "Hard": [
            ("Q1. What is the primary function of the enzyme DNA polymerase?", ["A) Unzipping the DNA double helix", "B) Synthesizing new DNA strands", "C) Repairing damaged DNA", "D) Transcribing RNA"], "B) Synthesizing new DNA strands"),
            ("Q2. Which structure in the cell is responsible for modifying, sorting, and packaging proteins for secretion?", ["A) Lysosome", "B) Golgi apparatus", "C) Endoplasmic reticulum", "D) Mitochondrion"], "B) Golgi apparatus"),
            ("Q3. What is the term for the process by which a single gene can produce multiple proteins?", ["A) Alternative splicing", "B) Gene duplication", "C) Transcription", "D) Translation"], "A) Alternative splicing"),
            ("Q4. Which hormone is primarily responsible for regulating metabolism and is produced by the thyroid gland?", ["A) Insulin", "B) Thyroxine", "C) Cortisol", "D) Adrenaline"], "B) Thyroxine"),
            ("Q5. What is the function of the enzyme telomerase?", ["A) Synthesizing telomeres", "B) Degrading mRNA", "C) Unwinding the DNA helix", "D) Splicing RNA"], "A) Synthesizing telomeres"),
            ("Q6. In which part of the human brain is the hippocampus located, and what is its primary function?", ["A) Cerebrum; motor control", "B) Brainstem; autonomic functions", "C) Limbic system; memory", "D) Cerebellum; balance"], "C) Limbic system; memory"),
            ("Q7. What is the name of the process by which cells undergo programmed cell death?", ["A) Necrosis", "B) Apoptosis", "C) Autophagy", "D) Differentiation"], "B) Apoptosis"),
            ("Q8. Which type of RNA is involved in the regulation of gene expression by degrading mRNA or blocking its translation?", ["A) mRNA", "B) tRNA", "C) rRNA", "D) miRNA"], "D) miRNA"),
            ("Q9. What is the role of the protein p53 in the cell cycle?", ["A) Stimulating cell division", "B) Inhibiting cell division", "C) Repairing DNA", "D) Initiating apoptosis"], "D) Initiating apoptosis"),
            ("Q10. Which metabolic pathway is used by cells to generate energy in the absence of oxygen?", ["A) Glycolysis", "B) Krebs cycle", "C) Electron transport chain", "D) Fermentation"], "D) Fermentation"),
            ("Q11. What is the function of the smooth endoplasmic reticulum in a cell?", ["A) Protein synthesis", "B) Lipid synthesis", "C) ATP production", "D) DNA replication"], "B) Lipid synthesis"),
            ("Q12. In genetics, what is the term for the observable physical or biochemical characteristics of an organism as determined by both genetic makeup and environmental influences?", ["A) Genotype", "B) Phenotype", "C) Allele", "D) Gene"], "B) Phenotype"),
            ("Q13. What is the primary structure of a protein?", ["A) Sequence of amino acids", "B) Alpha-helix and beta-sheet", "C) 3D folded shape", "D) Assembly of multiple polypeptides"], "A) Sequence of amino acids"),
            ("Q14. What is the function of the TATA box in eukaryotic promoters?", ["A) Enhancing translation", "B) Binding RNA polymerase", "C) Terminating transcription", "D) Splicing introns"], "B) Binding RNA polymerase"),
            ("Q15. Which organelle is primarily involved in the degradation of cellular waste and foreign material in animal cells?", ["A) Lysosome", "B) Peroxisome", "C) Mitochondrion", "D) Endoplasmic reticulum"], "A) Lysosome"),
            ("Q16. What is the name of the specialized region of the chromosome where the spindle fibers attach during cell division?", ["A) Centromere", "B) Telomere", "C) Origin of replication", "D) Promoter"], "A) Centromere"),
            ("Q17. In the context of population genetics, what is the Hardy-Weinberg equilibrium used to describe?", ["A) The migration rate of species", "B) The genetic variation within a population", "C) The mutation rate of alleles", "D) The rate of natural selection"], "B) The genetic variation within a population"),
            ("Q18. What is the primary function of the protein kinases in cellular signaling?", ["A) Dephosphorylation", "B) Phosphorylation", "C) Hydrolysis", "D) Oxidation"], "B) Phosphorylation"),
            ("Q19. Which type of cell division results in four genetically unique haploid cells?", ["A) Mitosis", "B) Binary fission", "C) Meiosis", "D) Budding"], "C) Meiosis"),
            ("Q20. What is the main role of cyclic AMP (cAMP) in cells?", ["A) Serving as a second messenger", "B) Catalyzing metabolic reactions", "C) Synthesizing proteins", "D) Breaking down carbohydrates"], "A) Serving as a second messenger")
]
    }
}